/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public liveness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public readiness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service dependencies are ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadyResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user and tenant context */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approved PawIt v1 product policy */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductSpec"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PawIt role and permission policies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role policies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RolePolicyList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hospital portal navigation sections */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Navigation sections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NavigationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top-level operational metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List appointments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Appointment list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentList"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a staff-managed appointment or pet-parent appointment request
         * @description Pet parents create requested appointments. Staff users with appointment management permission can create scheduled appointments. Telemedicine appointments use manually entered meeting links in v1.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAppointmentRequest"];
                };
            };
            responses: {
                /** @description Appointment created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentMutationResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an appointment with clinic cutoff enforcement */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Resource identifier. */
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CancelAppointmentRequest"];
                };
            };
            responses: {
                /** @description Appointment cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentMutationResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get appointment calendar data */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Calendar data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active queue entries */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queue entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueueEntryList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/walk-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a walk-in queue entry and linked appointment */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterWalkInRequest"];
                };
            };
            responses: {
                /** @description Walk-in registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueueMutationResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a queue entry as called */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Resource identifier. */
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["UpdateQueueBody"];
            responses: {
                200: components["responses"]["QueueMutationOK"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a queue entry into consultation */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Resource identifier. */
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["UpdateQueueBody"];
            responses: {
                200: components["responses"]["QueueMutationOK"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a queue entry and linked appointment */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Resource identifier. */
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["UpdateQueueBody"];
            responses: {
                200: components["responses"]["QueueMutationOK"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queue entry and linked appointment */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Resource identifier. */
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["UpdateQueueBody"];
            responses: {
                200: components["responses"]["QueueMutationOK"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dog/cat pet records */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pet records */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetRecordList"];
                    };
                };
            };
        };
        put?: never;
        /** Create a dog/cat pet record with first guardian */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePetRequest"];
                };
            };
            responses: {
                /** @description Pet created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetMutationResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a pet record with audit reason
         * @description PawIt never hard-deletes clinical records from the application API.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Resource identifier. */
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ArchivePetRequest"];
                };
            };
            responses: {
                /** @description Pet archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetMutationResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register uploaded pet document metadata
         * @description The file itself is stored through a signed upload flow. This endpoint records the document metadata once storage has accepted the object.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Safe retry key for mutation requests. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Resource identifier. */
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadPetDocumentRequest"];
                };
            };
            responses: {
                /** @description Document metadata registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetDocumentMutationResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pet records
         * @description Legacy alias for `/pets` while the hospital UI migrates to veterinary naming.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pet records */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PetRecordList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescription-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List veterinary prescription templates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prescription templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrescriptionTemplateList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinical-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clinical notes and consultations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Clinical notes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClinicalNoteList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List lab tests and diagnostic reports */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lab tests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabTestList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get billing metrics and invoices */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Billing dashboard */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant analytics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Analytics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get feedback metrics and reviews */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Feedback dashboard */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List veterinarians */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Veterinarians */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-pet-parent clinic staff */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Staff members */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @constant */
            status: "ok";
            /** @constant */
            service: "pawit-vetcare-api";
        };
        ReadyResponse: {
            /** @constant */
            status: "ready";
            /** Format: date-time */
            checkedAt: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        MeResponse: {
            user: {
                id: string;
                role: components["schemas"]["Role"];
                tenantId: string;
            };
            clinic: {
                name: string;
                type: string;
            };
        };
        ProductSpec: {
            /** @constant */
            productName: "PawIt VetCare";
            /** @constant */
            shortName: "PawIt";
            supportedSpecies: components["schemas"]["Species"][];
            supportedAppointmentTypes: components["schemas"]["AppointmentType"][];
            supportedAppointmentStatuses: components["schemas"]["AppointmentStatus"][];
            supportedLabStatuses: components["schemas"]["LabOrderStatus"][];
            /** @constant */
            paymentProvider: "stripe";
            /** @constant */
            currency: "USD";
            /** @constant */
            petParentAuth: "email_password";
            telemedicine: components["schemas"]["TelemedicineSpec"];
            labs: components["schemas"]["LabSpec"];
            cancellationPolicy: components["schemas"]["CancellationPolicy"];
            /** @constant */
            recordDeletionPolicy: "archive_cancel_void_only";
            /** @constant */
            aiAdvisoryEnabled: false;
            /** @constant */
            groomingEnabled: false;
            /** @constant */
            hipaaAligned: true;
        };
        TelemedicineSpec: {
            /** @constant */
            mode: "manual_meeting_link";
            /** @constant */
            builtInVideoRoomsEnabled: false;
        };
        LabSpec: {
            /** @constant */
            internalLabsEnabled: true;
            /** @constant */
            externalLabsEnabled: true;
            /** @constant */
            externalIntegrationMode: "manual_status_based";
            /** @constant */
            thirdPartyApiIntegrationInV1: false;
        };
        CancellationPolicy: {
            /** @constant */
            defaultCutoffHours: 24;
            /** @constant */
            tenantConfigurable: true;
            /** @constant */
            locationOverride: true;
            /** @constant */
            staffOverrideAllowed: true;
        };
        RolePolicyList: {
            items: components["schemas"]["RolePolicy"][];
        };
        RolePolicy: {
            role: components["schemas"]["Role"];
            description: string;
            permissions: string[];
            restrictions?: string[];
        };
        NavigationResponse: {
            sections: components["schemas"]["NavSection"][];
        };
        NavSection: {
            label: string;
            items: components["schemas"]["NavItem"][];
        };
        NavItem: {
            label: string;
            path: string;
            icon: string;
        };
        MetricList: {
            metrics: components["schemas"]["Metric"][];
        };
        Metric: {
            label: string;
            value: string;
            delta?: string;
            tone?: string;
        };
        AppointmentList: {
            items: components["schemas"]["Appointment"][];
        };
        Appointment: {
            id: string;
            petName: string;
            ownerName: string;
            primaryVeterinarian: string;
            additionalVeterinarians: string[];
            time: string;
            type: components["schemas"]["AppointmentType"];
            status: components["schemas"]["AppointmentStatus"];
            contact: string;
            meetingUrl?: string;
            reason: string;
        };
        CreateAppointmentRequest: {
            locationId: string;
            petId: string;
            type: components["schemas"]["AppointmentType"];
            reason: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            primaryVeterinarianId?: string;
            additionalVeterinarianIds?: string[];
            meetingUrl?: string;
            requestedByPetParent?: boolean;
        };
        CancelAppointmentRequest: {
            reason: string;
            staffOverride?: boolean;
        };
        AppointmentMutationResult: {
            appointment: components["schemas"]["Appointment"];
            idempotent?: boolean;
        };
        CalendarResponse: {
            /** Format: date */
            date: string;
            statusCounts: {
                [key: string]: number;
            };
            items: components["schemas"]["Appointment"][];
        };
        QueueEntryList: {
            items: components["schemas"]["QueueEntry"][];
        };
        QueueEntry: {
            id: string;
            petName: string;
            ownerName: string;
            species: components["schemas"]["Species"];
            priority: string;
            status: components["schemas"]["QueueStatus"];
            waitMins: number;
        };
        RegisterWalkInRequest: {
            locationId: string;
            petId: string;
            priority?: string;
            reason: string;
        };
        UpdateQueueRequest: {
            reason?: string;
        };
        QueueMutationResult: {
            queueEntry: components["schemas"]["QueueEntry"];
            idempotent?: boolean;
        };
        PetRecordList: {
            items: components["schemas"]["PetRecord"][];
        };
        PetRecord: {
            id: string;
            petName: string;
            ownerName: string;
            species: components["schemas"]["Species"];
            breed: string;
            age: string;
            sex: string;
            phone: string;
            lastVisit: string;
            vaccinesDue: number;
            openPlans: number;
            guardianCount: number;
            documentsCount: number;
        };
        CreatePetRequest: {
            locationId: string;
            name: string;
            species: components["schemas"]["Species"];
            breed?: string;
            sex?: string;
            estimatedAge?: string;
            guardianName: string;
            /** Format: email */
            guardianEmail?: string;
            relationship?: string;
            primaryGuardian?: boolean;
        };
        ArchivePetRequest: {
            reason: string;
        };
        PetMutationResult: {
            pet: components["schemas"]["PetRecord"];
            idempotent?: boolean;
        };
        UploadPetDocumentRequest: {
            title: string;
            documentType: string;
            objectPath: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        PetDocumentMutationResult: {
            document: components["schemas"]["PetDocument"];
            idempotent?: boolean;
        };
        PetDocument: {
            id: string;
            petId: string;
            title: string;
            documentType: string;
            objectPath: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            /** @enum {string} */
            status: "active" | "archived";
            /** Format: date-time */
            createdAt: string;
        };
        PrescriptionTemplateList: {
            items: components["schemas"]["PrescriptionTemplate"][];
        };
        PrescriptionTemplate: {
            id: string;
            name: string;
            condition: string;
            category: string;
            medications: string[];
            instructions: string;
        };
        ClinicalNoteList: {
            items: components["schemas"]["ClinicalNote"][];
        };
        ClinicalNote: {
            id: string;
            petName: string;
            ownerName: string;
            subject: string;
            status: string;
            /** Format: date-time */
            updatedAt: string;
            sharedWithPetParent: boolean;
        };
        LabTestList: {
            items: components["schemas"]["LabTest"][];
        };
        LabTest: {
            id: string;
            petName: string;
            ownerName: string;
            testType: string;
            labCenter: string;
            labType: string;
            status: components["schemas"]["LabOrderStatus"];
            reportUrl?: string;
            sharedWithPetParent: boolean;
        };
        BillingResponse: {
            metrics: components["schemas"]["Metric"][];
            invoices: components["schemas"]["Invoice"][];
        };
        Invoice: {
            id: string;
            petName: string;
            ownerName: string;
            /** Format: int64 */
            amount: number;
            status: string;
            dueDate: string;
        };
        Analytics: {
            metrics: components["schemas"]["Metric"][];
            speciesDistribution: {
                [key: string]: number;
            };
            appointmentStatus: {
                [key: string]: number;
            };
            revenueTrend: {
                [key: string]: string;
            };
            commonDiagnoses: components["schemas"]["Metric"][];
        };
        FeedbackResponse: {
            metrics: components["schemas"]["Metric"][];
            distribution: {
                [key: string]: number;
            };
            items: components["schemas"]["Feedback"][];
        };
        Feedback: {
            id: string;
            petName: string;
            ownerName: string;
            rating: number;
            comment: string;
            createdAt: string;
        };
        PersonList: {
            items: components["schemas"]["Person"][];
        };
        Person: {
            id: string;
            name: string;
            role: string;
            specialty?: string;
            email: string;
            status: string;
        };
        /** @enum {string} */
        Role: "SuperAdmin" | "ClinicAdmin" | "Veterinarian" | "Receptionist" | "VetTechnician" | "LabTechnician" | "PetParent";
        /** @enum {string} */
        Species: "dog" | "cat";
        /** @enum {string} */
        AppointmentType: "in_clinic" | "telemedicine" | "walk_in" | "follow_up" | "vaccination" | "lab_diagnostic" | "procedure_consult";
        /** @enum {string} */
        AppointmentStatus: "requested" | "scheduled" | "confirmed" | "checked_in" | "waiting" | "in_progress" | "completed" | "cancelled" | "no_show" | "needs_reschedule" | "rejected";
        /** @enum {string} */
        QueueStatus: "waiting" | "called" | "in_progress" | "completed" | "cancelled";
        /** @enum {string} */
        LabOrderStatus: "ordered" | "sample_collected" | "sent_out" | "in_progress" | "completed" | "cancelled";
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Role does not have required permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found in tenant scope */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description State conflict or idempotency-key conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Service dependency unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Queue entry updated */
        QueueMutationOK: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["QueueMutationResult"];
            };
        };
    };
    parameters: {
        /** @description Safe retry key for mutation requests. */
        IdempotencyKey: string;
        /** @description Resource identifier. */
        PathID: string;
        /** @description Local development only when PAWIT_ALLOW_DEV_AUTH=true. */
        DevTenantID: string;
        /** @description Local development only when PAWIT_ALLOW_DEV_AUTH=true. */
        DevUserID: string;
        /** @description Local development only when PAWIT_ALLOW_DEV_AUTH=true. */
        DevRole: components["schemas"]["Role"];
    };
    requestBodies: {
        UpdateQueueBody: {
            content: {
                "application/json": components["schemas"]["UpdateQueueRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
